export const week5 = `
# Week 5: Secrets Detection & DAST

## Overview
We tackle two distinct areas: finding hardcoded secrets before they leak, and attacking the running application from the outside using Dynamic Application Security Testing (DAST).

### Goals
- Implement Gitleaks in CI/CD.
- Handle secret false positives securely.
- Automate OWASP ZAP for DAST.
- Integrate Burp Dastardly.

### Deliverables
- A pipeline blocking secrets.
- An automated baseline DAST scan against a test environment.

---

## Day 1: Secrets Detection with Gitleaks

### Objective
Prevent AWS keys, API tokens, and passwords from entering the Git history.

### Theory (15 min)
- Entropy vs Regex matching.
- The danger of Git history (why deleting the file isn't enough).
- BFG Repo-Cleaner / \`git filter-repo\`.

### Hands-on (3 hours)
**Lab 1: Gitleaks Integration**
1. Add Gitleaks to your pipeline using the official Docker image.
2. Run it in \`--log-opts\` mode to scan only the commits in the current Push. (Scanning the whole repo takes too long in CI).
3. Commit a fake API key. Ensure the pipeline fails.

**Lab 2: Custom Rules and Exclusions**
1. Create a \`.gitleaks.toml\` configuration file.
2. Write a custom rule to detect a proprietary internal token format (e.g., \`CORP-SEC-[a-zA-Z0-9]{16}\`).
3. Add a false positive exception (allow-list) for a dummy test token used in unit tests.

---

## Day 2: DAST Fundamentals & OWASP ZAP

### Objective
Understand dynamic scanning and perform a baseline scan.

### Theory (20 min)
- SAST vs DAST.
- Spiders, Crawlers, and Active Scanners.
- Why DAST is slow and how to optimize it for CI/CD.

### Hands-on (3 hours)
**Lab: ZAP Baseline Scan**
1. Deploy a deliberately vulnerable application locally (e.g., OWASP Juice Shop) using Docker: \`docker run -d -p 3000:3000 bkimminich/juice-shop\`.
2. Pull the \`owasp/zap2docker-stable\` image.
3. Run the ZAP Baseline script: \`docker run -t owasp/zap2docker-stable zap-baseline.py -t http://<YOUR_IP>:3000\`.
4. Review the generated report. Notice how it finds missing headers and basic misconfigurations quickly.

---

## Day 3: Authenticated DAST & API Scanning

### Objective
Scan behind login screens and test REST APIs directly.

### Theory (15 min)
- Contexts, Sessions, and Authentication in ZAP.
- OpenAPI/Swagger scanning.

### Hands-on (3 hours)
**Lab: ZAP API Scan**
1. Deploy a sample API with an OpenAPI specification (e.g., \`vapi\` or crAPI).
2. Run the ZAP API scanner script: \`zap-api-scan.py -t http://<API_URL>/openapi.json -f openapi\`.
3. Integrate this into the GitLab pipeline. The application must be deployed to a "Review" or "Staging" environment in the CI job *before* the DAST job runs.

### Senior Engineer Tips
> "Never run a full Active Scan in a synchronous CI/CD pipeline. It takes hours. Run Baseline/API scans in the pipeline, and schedule full Active Scans asynchronously (e.g., nightly weekends)."

---

## Day 4: Burp Dastardly

### Objective
Use modern, CI-focused DAST tools.

### Theory (10 min)
- Introduction to Burp Dastardly (free CI DAST by PortSwigger).

### Hands-on (2 hours)
**Lab: Dastardly Integration**
1. Add Dastardly to your pipeline.
   \`\`\`yaml
   dastardly:
     image: public.ecr.aws/portswigger/dastardly:latest
     command: ["dastardly", "--target-url", "http://staging-app"]
   \`\`\`
2. Parse the JUnit XML output generated by Dastardly to fail the pipeline on High vulnerabilities.

---

## Day 5: Mini-Project

### The Staging Attacker
Create a comprehensive pipeline that:
1. Builds a Docker image of a simple web app.
2. Deploys the container using GitLab services or \`docker run\` in the CI job.
3. Waits for the application to be healthy.
4. Executes OWASP ZAP Baseline scan against the running container.
5. Fails the pipeline if cross-site scripting (XSS) is detected.
6. Tears down the container.
`;
